service: stripe-payment-api

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}

functions:
  createPayment:
    handler: handler.createPayment
    events:
      - http:
          path: create-payment
          method: post
          cors: true

plugins:
  - serverless-offline

package:
  individually: true

build:
  esbuild: true
