import { CategoryType } from './types/category';

const DATA: CategoryType[] = [
  {
    id: 'office',
    title: 'Office chairs',
    path: '/office',
    imageSrc: './img/category/office-chair.jpg',
    items: [
      {
        id: 'office-item-1',
        name: 'Q-118R',
        imageSrc: './img/products/office/q-118r.jpg',
        price: 126.1,
        filters: {
          width: 60,
          height: 115,
          depth: 64,
          color: 'gray',
          material: ['mesh', 'membrane fabric'],
          legs: 'metal',
          seatHeight: 47,
          seatDepth: 44,
          maxWeight: 100,
          specs: [
            'multiblock',
            'adjustable armrests',
            'adjustable backrest height',
            'adjustable headrest',
          ],
        },
      },
      {
        id: 'office-item-2',
        name: 'Q-080',
        imageSrc: './img/products/office/q-080.jpg',
        price: 153.2,
        filters: {
          width: 67,
          height: 125,
          depth: 66,
          color: 'black',
          material: ['fabric', 'membrane fabric'],
          legs: 'metal',
          seatHeight: 48,
          seatDepth: 50,
          maxWeight: 100,
          specs: [
            'tilt',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
            'headrest',
          ],
        },
      },
      {
        id: 'office-item-3',
        name: 'Q-718',
        imageSrc: './img/products/office/q-718.jpg',
        price: 204.7,
        filters: {
          width: 63,
          height: 108,
          depth: 66,
          color: 'black',
          material: ['mesh', 'membrane fabric'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 50,
          maxWeight: 110,
          specs: [
            'tilt',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
          ],
        },
      },
      {
        id: 'office-item-4',
        name: 'Q-080M',
        imageSrc: './img/products/office/q-080m.jpg',
        price: 153.8,
        filters: {
          width: 67,
          height: 125,
          depth: 66,
          color: 'gray',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 48,
          seatDepth: 50,
          maxWeight: 100,
          specs: [
            'tilt',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
            'headrest',
          ],
        },
      },
      {
        id: 'office-item-5',
        name: 'Q-724',
        imageSrc: './img/products/office/q-724.jpg',
        price: 161.4,
        filters: {
          width: 62,
          height: 105,
          depth: 66,
          color: 'gray',
          material: ['mesh', 'membrane fabric'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 49,
          maxWeight: 110,
          specs: [
            'tilt',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
          ],
        },
      },
      {
        id: 'office-item-6',
        name: 'Q-744',
        imageSrc: './img/products/office/q-744.jpg',
        price: 204.3,
        filters: {
          width: 62,
          height: 101,
          depth: 66,
          color: 'brown',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 43,
          seatDepth: 50,
          maxWeight: 110,
          specs: [
            'tilt',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
          ],
        },
      },
      {
        id: 'office-item-7',
        name: 'Q-320R',
        imageSrc: './img/products/office/q-320r.jpg',
        price: 107.1,
        filters: {
          width: 48,
          height: 103,
          depth: 64,
          color: 'gray-black',
          material: ['mesh', 'fabric'],
          legs: 'metal',
          seatHeight: 44,
          seatDepth: 44,
          maxWeight: 100,
          specs: ['tilt', 'adjustable armrests'],
        },
      },
      {
        id: 'office-item-8',
        name: 'Q-330R',
        imageSrc: './img/products/office/q-330r.jpg',
        price: 115.3,
        filters: {
          width: 62,
          height: 103,
          depth: 66,
          color: 'gray-black',
          material: ['mesh', 'fabric'],
          legs: 'plastic',
          seatHeight: 47,
          seatDepth: 48,
          maxWeight: 110,
          specs: ['tilt', 'adjustable armrests'],
        },
      },
      {
        id: 'office-item-9',
        name: 'Q-058',
        imageSrc: './img/products/office/q-058.jpg',
        price: 167.8,
        filters: {
          width: 65,
          height: 113,
          depth: 70,
          color: 'black',
          material: ['mesh', 'membrane fabric'],
          legs: 'plastic',
          seatHeight: 46,
          seatDepth: 50,
          maxWeight: 136,
          specs: [
            'multiblock',
            'adjustable armrests',
            'lumbar section',
            'headrest',
          ],
        },
      },
      {
        id: 'office-item-10',
        name: 'Q-345',
        imageSrc: './img/products/office/q-345.jpg',
        price: 107.9,
        filters: {
          width: 62,
          height: 118,
          depth: 70,
          color: 'gray',
          material: ['mesh', 'fabric'],
          legs: 'metal',
          seatHeight: 49,
          seatDepth: 47,
          maxWeight: 120,
          specs: ['tilt'],
        },
      },
      {
        id: 'office-item-11',
        name: 'Q-035',
        imageSrc: './img/products/office/q-035.jpg',
        price: 140.2,
        filters: {
          width: 59,
          height: 121,
          depth: 70,
          color: 'gray-white',
          material: ['fabric', 'eco-leather'],
          legs: 'metal',
          seatHeight: 46,
          seatDepth: 52,
          maxWeight: 130,
          specs: ['tilt'],
        },
      },
      {
        id: 'office-item-12',
        name: 'Q-025',
        imageSrc: './img/products/office/q-025.jpg',
        price: 91.1,
        filters: {
          width: 62,
          height: 111,
          depth: 70,
          color: 'black-gray',
          material: ['fabric', 'membrane fabric'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 50,
          maxWeight: 120,
          specs: ['tilt'],
        },
      },
    ],
  },
  {
    id: 'gaming',
    title: 'Gaming chairs',
    path: '/gaming',
    imageSrc: './img/category/gaming-chair.jpg',
    items: [
      {
        id: 'gaming-item-1',
        name: 'Winner Lux',
        imageSrc: './img/products/gaming/winner-lux.jpg',
        price: 450.2,
        filters: {
          width: 64,
          height: 114,
          depth: 72,
          color: 'black',
          material: ['mesh'],
          legs: 'aluminum',
          seatHeight: 44,
          seatDepth: 51,
          maxWeight: 136,
          specs: [
            'height sync mechanism',
            'adjustable armrests',
            'lumbar section',
            'adjustable backrest height',
            'headrest',
          ],
        },
      },
      {
        id: 'gaming-item-2',
        name: 'Viper',
        imageSrc: './img/products/gaming/viper.jpg',
        price: 180.3,
        filters: {
          width: 70,
          height: 127,
          depth: 70,
          color: 'black-blue',
          material: ['fabric'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 49,
          maxWeight: 130,
          specs: ['tilt', 'adjustable armrests'],
        },
      },
      {
        id: 'gaming-item-3',
        name: 'Revolt',
        imageSrc: './img/products/gaming/revolt.jpg',
        price: 223.4,
        filters: {
          width: 67,
          height: 120,
          depth: 70,
          color: 'black-red',
          material: ['eco-leather', 'mash'],
          legs: 'plastic',
          seatHeight: 48,
          seatDepth: 51,
          maxWeight: 120,
          specs: ['multiblock', 'adjustable armrests', 'rubber wheels'],
        },
      },
      {
        id: 'gaming-item-4',
        name: 'Q-229',
        imageSrc: './img/products/gaming/q-229.jpg',
        price: 185.8,
        filters: {
          width: 117,
          height: 66,
          depth: 70,
          color: 'gray-black',
          material: ['membrane fabric'],
          legs: 'plastic',
          seatHeight: 47,
          seatDepth: 50,
          maxWeight: 120,
          specs: ['tilt', 'multiblock', 'adjustable armrests'],
        },
      },
      {
        id: 'gaming-item-5',
        name: 'Dakar',
        imageSrc: './img/products/gaming/dakar.jpg',
        price: 33.9,
        filters: {
          width: 63,
          height: 106,
          depth: 64,
          color: 'black-red',
          material: ['fabric'],
          legs: 'plastic',
          seatHeight: 43,
          seatDepth: 48,
          maxWeight: 120,
          specs: ['tilt', 'rubber wheels'],
        },
      },
      {
        id: 'gaming-item-6',
        name: 'Zenvo',
        imageSrc: './img/products/gaming/zenvo.jpg',
        price: 157.8,
        filters: {
          width: 66,
          height: 122,
          depth: 70,
          color: 'black-gray',
          material: ['fabric'],
          legs: 'plastic',
          seatHeight: 45,
          seatDepth: 48,
          maxWeight: 130,
          specs: ['tilt'],
        },
      },
      {
        id: 'gaming-item-7',
        name: 'Q-939',
        imageSrc: './img/products/gaming/q-939.jpg',
        price: 134.2,
        filters: {
          width: 56,
          height: 108,
          depth: 70,
          color: 'black-gray',
          material: ['mesh', 'fabric'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 48,
          maxWeight: 120,
          specs: ['tilt', 'multiblock', 'extendable footrest'],
        },
      },
      {
        id: 'gaming-item-8',
        name: 'Q-095',
        imageSrc: './img/products/gaming/q-095.jpg',
        price: 118.1,
        filters: {
          width: 60,
          height: 117,
          depth: 68,
          color: 'black-gray',
          material: ['mesh', 'fabric'],
          legs: 'plastic',
          seatHeight: 46,
          seatDepth: 50,
          maxWeight: 120,
          specs: ['tilt', 'multiblock', 'rubber wheels', 'headrest'],
        },
      },
      {
        id: 'gaming-item-9',
        name: 'Q-019',
        imageSrc: './img/products/gaming/q-019.jpg',
        price: 115.2,
        filters: {
          width: 61,
          height: 112,
          depth: 70,
          color: 'black',
          material: ['eco-leather', 'membrane fabric'],
          legs: 'plastic',
          seatHeight: 40,
          seatDepth: 50,
          maxWeight: 120,
          specs: ['tilt'],
        },
      },
      {
        id: 'gaming-item-10',
        name: 'Q-724H',
        imageSrc: './img/products/gaming/q-724h.jpg',
        price: 185.4,
        filters: {
          width: 62,
          height: 122,
          depth: 66,
          color: 'black',
          material: ['fabric', 'membrane fabric'],
          legs: 'plastic',
          seatHeight: 45,
          seatDepth: 49,
          maxWeight: 120,
          specs: [
            'tilt',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
            'headrest',
          ],
        },
      },
      {
        id: 'gaming-item-11',
        name: 'Winner',
        imageSrc: './img/products/gaming/winner.jpg',
        price: 366.5,
        filters: {
          width: 64,
          height: 114,
          depth: 72,
          color: 'black',
          material: ['mesh'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 51,
          maxWeight: 136,
          specs: [
            'height sync mechanism',
            'multiblock',
            'adjustable armrests',
            'lumbar section',
            'adjustable backrest depth',
            'headrest',
          ],
        },
      },
      {
        id: 'gaming-item-12',
        name: 'Devon',
        imageSrc: './img/products/gaming/devon.jpg',
        price: 276.5,
        filters: {
          width: 68,
          height: 119,
          depth: 70,
          color: 'gray',
          material: ['mesh'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 50,
          maxWeight: 120,
          specs: [
            'multiblock',
            'adjustable armrests',
            'lumbar section',
            'headrest',
          ],
        },
      },
    ],
  },
  {
    id: 'dining',
    title: 'Dining chairs',
    path: '/dining',
    imageSrc: './img/category/dining-chair.jpg',
    items: [
      {
        id: 'dining-item-1',
        name: 'Mike Velvet',
        imageSrc: './img/products/dining/mike-velvet.jpg',
        price: 45.6,
        filters: {
          width: 48,
          height: 86,
          depth: 46,
          color: 'black',
          material: ['velvet fabric'],
          legs: 'metal',
          seatHeight: 47,
          seatDepth: 41,
          maxWeight: 100,
        },
      },
      {
        id: 'dining-item-2',
        name: 'CD-56',
        imageSrc: './img/products/dining/cd-56.jpg',
        price: 64.5,
        filters: {
          width: 40,
          height: 85,
          depth: 48,
          color: 'white',
          material: ['wood'],
          legs: 'wood',
          seatHeight: 45,
          seatDepth: 37,
          maxWeight: 130,
        },
      },
      {
        id: 'dining-item-3',
        name: 'Brando',
        imageSrc: './img/products/dining/brando.jpg',
        price: 69.9,
        filters: {
          width: 45,
          height: 76,
          depth: 50,
          color: 'gray',
          material: ['fabric'],
          legs: 'wood',
          seatHeight: 45,
          seatDepth: 40,
          maxWeight: 130,
        },
      },
      {
        id: 'dining-item-4',
        name: 'CD-61',
        imageSrc: './img/products/dining/cd-61.jpg',
        price: 87.7,
        filters: {
          width: 43,
          height: 76,
          depth: 52,
          color: 'gray',
          material: ['fabric'],
          legs: 'wood',
          seatHeight: 47,
          seatDepth: 42,
          maxWeight: 120,
        },
      },
      {
        id: 'dining-item-5',
        name: 'Fox',
        imageSrc: './img/products/dining/fox.jpg',
        price: 40.2,
        filters: {
          width: 44,
          height: 83,
          depth: 50,
          color: 'gray',
          material: ['fabric'],
          legs: 'wood',
          seatHeight: 48,
          seatDepth: 40,
          maxWeight: 120,
        },
      },
      {
        id: 'dining-item-6',
        name: 'Ego',
        imageSrc: './img/products/dining/ego.jpg',
        price: 53.7,
        filters: {
          width: 58,
          height: 80,
          depth: 50,
          color: 'white',
          material: ['plastic'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 42,
          maxWeight: 130,
        },
      },
      {
        id: 'dining-item-7',
        name: 'Corral-A',
        imageSrc: './img/products/dining/corral-a.jpg',
        price: 42.9,
        filters: {
          width: 46,
          height: 75,
          depth: 50,
          color: 'black',
          material: ['plastic'],
          legs: 'metal',
          seatHeight: 46,
          seatDepth: 44,
          maxWeight: 120,
        },
      },
      {
        id: 'dining-item-8',
        name: 'Karl',
        imageSrc: './img/products/dining/karl.jpg',
        price: 94.2,
        filters: {
          width: 49,
          height: 77,
          depth: 50,
          color: 'gray',
          material: ['fabric'],
          legs: 'wood',
          seatHeight: 47,
          seatDepth: 40,
          maxWeight: 120,
        },
      },
      {
        id: 'dining-item-9',
        name: 'Kris',
        imageSrc: './img/products/dining/kris.jpg',
        price: 45.6,
        filters: {
          width: 49,
          height: 83,
          depth: 51,
          color: 'gray',
          material: ['eco-leather', 'plastic'],
          legs: 'wood',
          seatHeight: 46,
          seatDepth: 41,
          maxWeight: 130,
        },
      },
      {
        id: 'dining-item-10',
        name: 'MN-SC',
        imageSrc: './img/products/dining/mn-sc.jpg',
        price: 88.8,
        filters: {
          width: 45,
          height: 96,
          depth: 52,
          color: 'brown',
          material: ['fabric'],
          legs: 'wood',
          seatHeight: 48,
          seatDepth: 42,
          maxWeight: 120,
        },
      },
      {
        id: 'dining-item-11',
        name: 'Mosso',
        imageSrc: './img/products/dining/mosso.jpg',
        price: 64.5,
        filters: {
          width: 41,
          height: 78,
          depth: 53,
          color: 'white',
          material: ['mdf'],
          legs: 'wood',
          seatHeight: 45,
          seatDepth: 43,
          maxWeight: 120,
        },
      },
      {
        id: 'dining-item-12',
        name: 'Moris',
        imageSrc: './img/products/dining/moris.jpg',
        price: 40.2,
        filters: {
          width: 46,
          height: 81,
          depth: 48,
          color: 'black',
          material: ['plastic'],
          legs: 'wood',
          seatHeight: 44,
          seatDepth: 37,
          maxWeight: 130,
        },
      },
      {
        id: 'dining-item-13',
        name: 'Smart-II',
        imageSrc: './img/products/dining/smart-ii.jpg',
        price: 37.5,
        filters: {
          width: 43,
          height: 78,
          depth: 48,
          color: 'white',
          material: ['wood'],
          legs: 'wood',
          seatHeight: 47,
          seatDepth: 40,
          maxWeight: 100,
        },
      },
      {
        id: 'dining-item-14',
        name: 'Glis-II',
        imageSrc: './img/products/dining/glis-ii.jpg',
        price: 56.4,
        filters: {
          width: 52,
          height: 81,
          depth: 57,
          color: 'beige',
          material: ['plastic'],
          legs: 'plastic',
          seatHeight: 45,
          seatDepth: 43,
          maxWeight: 150,
        },
      },
    ],
  },
  {
    id: 'soft',
    title: 'Soft chairs',
    path: '/soft',
    imageSrc: './img/category/soft-chair.jpg',
    items: [
      {
        id: 'soft-item-1',
        name: 'Servio Brego',
        imageSrc: './img/products/soft/servio-brego.jpg',
        price: 91.5,
        filters: {
          width: 55,
          height: 88,
          depth: 58,
          color: 'beige',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 50,
          seatDepth: 45,
          maxWeight: 100,
          specs: ['180deg auto return', 'pocket springs'],
        },
      },
      {
        id: 'soft-item-2',
        name: 'Wind Brego',
        imageSrc: './img/products/soft/wind-brego.jpg',
        price: 161.6,
        filters: {
          width: 66,
          height: 90,
          depth: 65,
          color: 'light beige',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 45,
          maxWeight: 120,
          specs: ['180deg auto return', 'pocket springs'],
        },
      },
      {
        id: 'soft-item-3',
        name: 'Nuvo Velvet',
        imageSrc: './img/products/soft/nuvo-velvet.jpg',
        price: 174.1,
        filters: {
          width: 62,
          height: 86,
          depth: 63,
          color: 'dark beige',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 50,
          seatDepth: 47,
          maxWeight: 120,
          specs: ['pillow included'],
        },
      },
      {
        id: 'soft-item-4',
        name: 'Hugo Brego',
        imageSrc: './img/products/soft/hugo-brego.jpg',
        price: 129.3,
        filters: {
          width: 58,
          height: 90,
          depth: 60,
          color: 'beige',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 49,
          seatDepth: 46,
          maxWeight: 120,
          specs: ['180deg auto return', 'pocket springs'],
        },
      },
      {
        id: 'soft-item-5',
        name: 'Borgo Raven',
        imageSrc: './img/products/soft/borgo-raven.jpg',
        price: 129.3,
        filters: {
          width: 58,
          height: 87,
          depth: 60,
          color: 'dark gray',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 50,
          seatDepth: 45,
          maxWeight: 120,
          specs: ['180deg auto return'],
        },
      },
      {
        id: 'soft-item-6',
        name: 'Cherry Velvet',
        imageSrc: './img/products/soft/cherry-velvet.jpg',
        price: 91.5,
        filters: {
          width: 57,
          height: 87,
          depth: 58,
          color: 'cappuccino',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 48,
          seatDepth: 43,
          maxWeight: 120,
        },
      },
      {
        id: 'soft-item-7',
        name: 'Azalia D Brego',
        imageSrc: './img/products/soft/azalia-d-brego.jpg',
        price: 142.7,
        filters: {
          width: 61,
          height: 86,
          depth: 58,
          color: 'light beige',
          material: ['fabric'],
          legs: 'wood',
          seatHeight: 50,
          seatDepth: 44,
          maxWeight: 110,
          specs: ['180deg auto return'],
        },
      },
      {
        id: 'soft-item-8',
        name: 'Remo Brego',
        imageSrc: './img/products/soft/remo-brego.jpg',
        price: 123.9,
        filters: {
          width: 60,
          height: 84,
          depth: 61,
          color: 'light beige',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 48,
          seatDepth: 40,
          maxWeight: 120,
          specs: ['180deg auto return'],
        },
      },
      {
        id: 'soft-item-9',
        name: 'Metro Bjorn',
        imageSrc: './img/products/soft/metro-bjorn.jpg',
        price: 134.7,
        filters: {
          width: 57,
          height: 84,
          depth: 63,
          color: 'navy',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 49,
          seatDepth: 45,
          maxWeight: 120,
          specs: ['180deg auto return', 'pocket springs'],
        },
      },
      {
        id: 'soft-item-10',
        name: 'Basil Vardo',
        imageSrc: './img/products/soft/basil-vardo.jpg',
        price: 148.1,
        filters: {
          width: 61,
          height: 89,
          depth: 66,
          color: 'beige',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 49,
          seatDepth: 43,
          maxWeight: 120,
          specs: ['180deg auto return', 'pocket springs'],
        },
      },
      {
        id: 'soft-item-11',
        name: 'Mango Velvet',
        imageSrc: './img/products/soft/mango-velvet.jpg',
        price: 76.9,
        filters: {
          width: 57,
          height: 83,
          depth: 60,
          color: 'gray',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 49,
          seatDepth: 45,
          maxWeight: 120,
          specs: ['180deg auto return'],
        },
      },
      {
        id: 'soft-item-12',
        name: 'Monte Sztruks',
        imageSrc: './img/products/soft/monte-sztruks.jpg',
        price: 129.3,
        filters: {
          width: 59,
          height: 87,
          depth: 56,
          color: 'green',
          material: ['corduroy'],
          legs: 'metal',
          seatHeight: 50,
          seatDepth: 46,
          maxWeight: 120,
        },
      },
    ],
  },
  {
    id: 'bar',
    title: 'Bar chairs',
    path: '/bar',
    imageSrc: './img/category/bar-chair.jpg',
    items: [
      {
        id: 'bar-item-1',
        name: 'Mila H-2 Velvet',
        imageSrc: './img/products/bar/mila-h2-velvet.jpg',
        price: 64.5,
        filters: {
          width: 43,
          height: 87,
          depth: 48,
          color: 'black',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 60,
          seatDepth: 40,
          maxWeight: 110,
        },
      },
      {
        id: 'bar-item-2',
        name: 'Colin B Velvet H-2',
        imageSrc: './img/products/bar/colin-b-h2-velvet.jpg',
        price: 107.7,
        filters: {
          width: 48,
          height: 88,
          depth: 50,
          color: 'gray',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 60,
          seatDepth: 42,
          maxWeight: 140,
        },
      },
      {
        id: 'bar-item-3',
        name: 'C-105',
        imageSrc: './img/products/bar/c-105.jpg',
        price: 58.8,
        filters: {
          width: 42,
          height: 96,
          depth: 47,
          color: 'black',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 65,
          seatDepth: 39,
          maxWeight: 90,
        },
      },
      {
        id: 'bar-item-4',
        name: 'C-617',
        imageSrc: './img/products/bar/c-617.jpg',
        price: 96.9,
        filters: {
          width: 42,
          height: 99,
          depth: 48,
          color: 'black',
          material: ['eco-leather'],
          legs: 'metal',
          seatHeight: 65,
          seatDepth: 42,
          maxWeight: 110,
        },
      },
      {
        id: 'bar-item-5',
        name: 'Chic H-2 Velvet',
        imageSrc: './img/products/bar/chic-h2-velvet.jpg',
        price: 69.9,
        filters: {
          width: 45,
          height: 92,
          depth: 50,
          color: 'green',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 60,
          seatDepth: 37,
          maxWeight: 120,
        },
      },
      {
        id: 'bar-item-6',
        name: 'Cherry H-2 Velvet',
        imageSrc: './img/products/bar/cherry-h2-velvet.jpg',
        price: 102.3,
        filters: {
          width: 56,
          height: 86,
          depth: 56,
          color: 'beige',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 60,
          seatDepth: 42,
          maxWeight: 110,
        },
      },
      {
        id: 'bar-item-7',
        name: 'Chic H-1 Velvet',
        imageSrc: './img/products/bar/chic-h1-velvet.jpg',
        price: 75.3,
        filters: {
          width: 45,
          height: 109,
          depth: 54,
          color: 'gray',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 77,
          seatDepth: 37,
          maxWeight: 120,
        },
      },
      {
        id: 'bar-item-8',
        name: 'Cherry H-1 Velvet',
        imageSrc: './img/products/bar/cherry-h1-velvet.jpg',
        price: 107.7,
        filters: {
          width: 56,
          height: 105,
          depth: 56,
          color: 'gray',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 76,
          seatDepth: 40,
          maxWeight: 110,
        },
      },
      {
        id: 'bar-item-9',
        name: 'C-105 Velvet',
        imageSrc: './img/products/bar/c-105-velvet.jpg',
        price: 61.8,
        filters: {
          width: 42,
          height: 96,
          depth: 47,
          color: 'green',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 65,
          seatDepth: 39,
          maxWeight: 90,
        },
      },
      {
        id: 'bar-item-10',
        name: 'Piano B H-2 Velvet',
        imageSrc: './img/products/bar/piano-b-h2-velvet.jpg',
        price: 78.0,
        filters: {
          width: 47,
          height: 88,
          depth: 56,
          color: 'black',
          material: ['fabric velvet'],
          legs: 'metal',
          seatHeight: 60,
          seatDepth: 42,
          maxWeight: 110,
        },
      },
      {
        id: 'bar-item-11',
        name: 'Sting',
        imageSrc: './img/products/bar/sting.jpg',
        price: 59.1,
        filters: {
          width: 49,
          height: 82,
          depth: 47,
          color: 'white',
          material: ['plastic'],
          legs: 'metal',
          seatHeight: 75,
          seatDepth: 42,
          maxWeight: 130,
        },
      },
      {
        id: 'bar-item-12',
        name: 'Trix H-1',
        imageSrc: './img/products/bar/trix-h1.jpg',
        price: 118.5,
        filters: {
          width: 46,
          height: 109,
          depth: 54,
          color: 'gray',
          material: ['fabric'],
          legs: 'metal',
          seatHeight: 78,
          seatDepth: 42,
          maxWeight: 120,
        },
      },
    ],
  },
  {
    id: 'children',
    title: "Children's chairs",
    path: '/children',
    imageSrc: './img/category/childrens-chair.jpg',
    items: [
      {
        id: 'children-item-1',
        name: 'Q-333',
        imageSrc: './img/products/children/q-333.jpg',
        price: 93.1,
        filters: {
          width: 65,
          height: 100,
          depth: 64,
          color: 'blue-black',
          material: ['fabric', 'mesh'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 47,
          maxWeight: 100,
          specs: ['tilt', 'adjustable armrests', 'lumbar section'],
        },
      },
      {
        id: 'children-item-2',
        name: 'Q-G2',
        imageSrc: './img/products/children/q-g2.jpg',
        price: 60.7,
        filters: {
          width: 48,
          height: 84,
          depth: 64,
          color: 'blue-black',
          material: ['membrane fabric'],
          legs: 'plastic',
          seatHeight: 38,
          seatDepth: 41,
          maxWeight: 80,
        },
      },
      {
        id: 'children-item-3',
        name: 'Q-118R',
        imageSrc: './img/products/children/q-118r.jpg',
        price: 126.6,
        filters: {
          width: 60,
          height: 115,
          depth: 64,
          color: 'gray',
          material: ['mesh', 'membrane fabric'],
          legs: 'metal',
          seatHeight: 47,
          seatDepth: 44,
          maxWeight: 100,
          specs: ['multiblock', 'headrest', 'adjustable backrest height'],
        },
      },
      {
        id: 'children-item-4',
        name: 'Q-330',
        imageSrc: './img/products/children/q-330.jpg',
        price: 102.3,
        filters: {
          width: 62,
          height: 103,
          depth: 66,
          color: 'yellow',
          material: ['fabric', 'mesh'],
          legs: 'plastic',
          seatHeight: 47,
          seatDepth: 48,
          maxWeight: 110,
          specs: ['tilt'],
        },
      },
      {
        id: 'children-item-5',
        name: 'Q-328H',
        imageSrc: './img/products/children/q-328h.jpg',
        price: 129.3,
        filters: {
          width: 62,
          height: 97,
          depth: 68,
          color: 'orange',
          material: ['fabric', 'mesh'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 48,
          maxWeight: 136,
          specs: ['multiblock', 'headrest'],
        },
      },
      {
        id: 'children-item-6',
        name: 'Q-328',
        imageSrc: './img/products/children/q-328.jpg',
        price: 102.3,
        filters: {
          width: 62,
          height: 97,
          depth: 68,
          color: 'blue',
          material: ['fabric', 'mesh'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 48,
          maxWeight: 136,
          specs: ['tilt'],
        },
      },
      {
        id: 'children-item-7',
        name: 'Q-320',
        imageSrc: './img/products/children/q-320.jpg',
        price: 91.5,
        filters: {
          width: 60,
          height: 93,
          depth: 64,
          color: 'pink',
          material: ['membrane fabric'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 44,
          maxWeight: 100,
          specs: ['tilt'],
        },
      },
      {
        id: 'children-item-8',
        name: 'Q-026',
        imageSrc: './img/products/children/q-026.jpg',
        price: 88.8,
        filters: {
          width: 59,
          height: 107,
          depth: 64,
          color: 'pink',
          material: ['membrane fabric', 'mesh'],
          legs: 'plastic',
          seatHeight: 44,
          seatDepth: 48,
          maxWeight: 100,
          specs: ['tilt'],
        },
      },
      {
        id: 'children-item-9',
        name: 'Q-639',
        imageSrc: './img/products/children/q-639.jpg',
        price: 129.3,
        filters: {
          width: 64,
          height: 113,
          depth: 54,
          color: 'gray',
          material: ['membrane fabric'],
          legs: 'metal',
          seatHeight: 48,
          seatDepth: 43,
          maxWeight: 120,
          specs: ['tilt', 'adjustable armrests', 'headrest'],
        },
      },
      {
        id: 'children-item-10',
        name: 'Q-121',
        imageSrc: './img/products/children/q-121.jpg',
        price: 58,
        filters: {
          width: 41,
          height: 74,
          depth: 56,
          color: 'black',
          material: ['membrane fabric'],
          legs: 'plastic',
          seatHeight: 43,
          seatDepth: 41,
          maxWeight: 100,
          specs: ['tilt', 'adjustable armrests', 'lumbar section'],
        },
      },
      {
        id: 'children-item-11',
        name: 'Q-025',
        imageSrc: './img/products/children/q-025.jpg',
        price: 91.5,
        filters: {
          width: 62,
          height: 111,
          depth: 64,
          color: 'yellow-black',
          material: ['membrane fabric'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 50,
          maxWeight: 120,
          specs: ['tilt'],
        },
      },
      {
        id: 'children-item-12',
        name: 'Q-022',
        imageSrc: './img/products/children/q-022.jpg',
        price: 96.9,
        filters: {
          width: 51,
          height: 87,
          depth: 56,
          color: 'pink',
          material: ['eco-leather'],
          legs: 'metal',
          seatHeight: 45,
          seatDepth: 40,
          maxWeight: 100,
        },
      },
    ],
  },
];

//For adding firestore data
// useEffect(() => {
//   addCollectionsAndDocuments('categories', DATA);
// }, []);

export default DATA;
