import { CategoryType } from './types/category';

const DATA: CategoryType[] = [
  {
    id: 'office',
    title: 'Office chairs',
    path: '/office',
    imageSrc: './img/category/office-chair.jpg',
    items: [
      {
        id: 'office-item-1',
        name: 'Q-118R',
        imageSrc: './img/products/office/q-118r.jpg',
        price: 25,
      },
      {
        id: 'office-item-2',
        name: 'Q-080',
        imageSrc: './img/products/office/q-080.jpg',
        price: 18,
      },
      {
        id: 'office-item-3',
        name: 'Q-718',
        imageSrc: './img/products/office/q-718.jpg',
        price: 22,
      },
      {
        id: 'office-item-4',
        name: 'Q-080M',
        imageSrc: './img/products/office/q-080m.jpg',
        price: 20,
      },
      {
        id: 'office-item-5',
        name: 'Q-724',
        imageSrc: './img/products/office/q-724.jpg',
        price: 16,
      },
      {
        id: 'office-item-6',
        name: 'Q-744',
        imageSrc: './img/products/office/q-744.jpg',
        price: 15,
      },
      {
        id: 'office-item-7',
        name: 'Q-320R',
        imageSrc: './img/products/office/q-320r.jpg',
        price: 20,
      },
      {
        id: 'office-item-8',
        name: 'Q-330R',
        imageSrc: './img/products/office/q-330r.jpg',
        price: 19,
      },
      {
        id: 'office-item-9',
        name: 'Q-058',
        imageSrc: './img/products/office/q-058.jpg',
        price: 21,
      },
      {
        id: 'office-item-10',
        name: 'Q-345',
        imageSrc: './img/products/office/q-345.jpg',
        price: 16,
      },
      {
        id: 'office-item-11',
        name: 'Q-035',
        imageSrc: './img/products/office/q-035.jpg',
        price: 11,
      },
      {
        id: 'office-item-12',
        name: 'Q-025',
        imageSrc: './img/products/office/q-025.jpg',
        price: 28,
      },
    ],
  },
  {
    id: 'gaming',
    title: 'Gaming chairs',
    path: '/gaming',
    imageSrc: './img/category/gaming-chair.jpg',
    items: [
      {
        id: 'gaming-item-1',
        name: 'Winner Lux',
        imageSrc: './img/products/gaming/winner-lux.jpg',
        price: 35,
      },
      {
        id: 'gaming-item-2',
        name: 'Viper',
        imageSrc: './img/products/gaming/viper.jpg',
        price: 29,
      },
      {
        id: 'gaming-item-3',
        name: 'Revolt',
        imageSrc: './img/products/gaming/revolt.jpg',
        price: 31,
      },
      {
        id: 'gaming-item-4',
        name: 'Q-229',
        imageSrc: './img/products/gaming/q-229.jpg',
        price: 27,
      },
      {
        id: 'gaming-item-5',
        name: 'Dakar',
        imageSrc: './img/products/gaming/dakar.jpg',
        price: 33,
      },
      {
        id: 'gaming-item-6',
        name: 'Zenvo',
        imageSrc: './img/products/gaming/zenvo.jpg',
        price: 34,
      },
      {
        id: 'gaming-item-7',
        name: 'Q-939',
        imageSrc: './img/products/gaming/q-939.jpg',
        price: 31,
      },
      {
        id: 'gaming-item-8',
        name: 'Q-095',
        imageSrc: './img/products/gaming/q-095.jpg',
        price: 30,
      },
      {
        id: 'gaming-item-9',
        name: 'Q-019',
        imageSrc: './img/products/gaming/q-019.jpg',
        price: 37,
      },
      {
        id: 'gaming-item-10',
        name: 'Q-724H',
        imageSrc: './img/products/gaming/q-724h.jpg',
        price: 30,
      },
      {
        id: 'gaming-item-11',
        name: 'Winner',
        imageSrc: './img/products/gaming/winner.jpg',
        price: 33,
      },
      {
        id: 'gaming-item-12',
        name: 'Devon',
        imageSrc: './img/products/gaming/devon.jpg',
        price: 35,
      },
    ],
  },
  {
    id: 'dining',
    title: 'Dining chairs',
    path: '/dining',
    imageSrc: './img/category/dining-chair.jpg',
    items: [
      {
        id: 'dining-item-1',
        name: 'Mike Velvet',
        imageSrc: './img/products/dining/mike-velvet.jpg',
        price: 16,
      },
      {
        id: 'dining-item-2',
        name: 'CD-56',
        imageSrc: './img/products/dining/cd-56.jpg',
        price: 14,
      },
      {
        id: 'dining-item-3',
        name: 'Brando',
        imageSrc: './img/products/dining/brando.jpg',
        price: 17,
      },
      {
        id: 'dining-item-4',
        name: 'CD-61',
        imageSrc: './img/products/dining/cd-61.jpg',
        price: 19,
      },
      {
        id: 'dining-item-5',
        name: 'Fox',
        imageSrc: './img/products/dining/fox.jpg',
        price: 18,
      },
      {
        id: 'dining-item-6',
        name: 'Ego',
        imageSrc: './img/products/dining/ego.jpg',
        price: 20,
      },
      {
        id: 'dining-item-7',
        name: 'Corral-A',
        imageSrc: './img/products/dining/corral-a.jpg',
        price: 17,
      },
      {
        id: 'dining-item-8',
        name: 'Karl',
        imageSrc: './img/products/dining/karl.jpg',
        price: 19,
      },
      {
        id: 'dining-item-9',
        name: 'Kris',
        imageSrc: './img/products/dining/kris.jpg',
        price: 18,
      },
      {
        id: 'dining-item-10',
        name: 'MN-SC',
        imageSrc: './img/products/dining/mn-sc.jpg',
        price: 26,
      },
      {
        id: 'dining-item-11',
        name: 'Mosso',
        imageSrc: './img/products/dining/mosso.jpg',
        price: 18,
      },
      {
        id: 'dining-item-12',
        name: 'Moris',
        imageSrc: './img/products/dining/moris.jpg',
        price: 20,
      },
      {
        id: 'dining-item-13',
        name: 'Smart-II',
        imageSrc: './img/products/dining/smart-ii.jpg',
        price: 14,
      },
      {
        id: 'dining-item-14',
        name: 'Glis-II',
        imageSrc: './img/products/dining/glis-ii.jpg',
        price: 17,
      },
    ],
  },
  {
    id: 'soft',
    title: 'Soft chairs',
    path: '/soft',
    imageSrc: './img/category/soft-chair.jpg',
    items: [
      {
        id: 'soft-item-1',
        name: 'Servio Brego',
        imageSrc: './img/products/soft/servio-brego.jpg',
        price: 25,
      },
      {
        id: 'soft-item-2',
        name: 'Wind Brego',
        imageSrc: './img/products/soft/wind-brego.jpg',
        price: 18,
      },
      {
        id: 'soft-item-3',
        name: 'Nuvo Velvet',
        imageSrc: './img/products/soft/nuvo-velvet.jpg',
        price: 22,
      },
      {
        id: 'soft-item-4',
        name: 'Hugo Brego',
        imageSrc: './img/products/soft/hugo-brego.jpg',
        price: 20,
      },
      {
        id: 'soft-item-5',
        name: 'Borgo Raven',
        imageSrc: './img/products/soft/borgo-raven.jpg',
        price: 23,
      },
      {
        id: 'soft-item-6',
        name: 'Cherry Velvet',
        imageSrc: './img/products/soft/cherry-velvet.jpg',
        price: 21,
      },
      {
        id: 'soft-item-7',
        name: 'Azalia D Brego',
        imageSrc: './img/products/soft/azalia-d-brego.jpg',
        price: 21,
      },
      {
        id: 'soft-item-8',
        name: 'Remo Brego',
        imageSrc: './img/products/soft/remo-brego.jpg',
        price: 22,
      },
      {
        id: 'soft-item-9',
        name: 'Metro Bjorn',
        imageSrc: './img/products/soft/metro-bjorn.jpg',
        price: 20,
      },
      {
        id: 'soft-item-10',
        name: 'Basil Vardo',
        imageSrc: './img/products/soft/basil-vardo.jpg',
        price: 18,
      },
      {
        id: 'soft-item-11',
        name: 'Mango Velvet',
        imageSrc: './img/products/soft/mango-velvet.jpg',
        price: 21,
      },
      {
        id: 'soft-item-12',
        name: 'Monte Sztruks',
        imageSrc: './img/products/soft/monte-sztruks.jpg',
        price: 24,
      },
    ],
  },
  {
    id: 'bar',
    title: 'Bar chairs',
    path: '/bar',
    imageSrc: './img/category/bar-chair.jpg',
    items: [
      {
        id: 'bar-item-1',
        name: 'Mila H-2 Velvet',
        imageSrc: './img/products/bar/mila-h2-velvet.jpg',
        price: 18,
      },
      {
        id: 'bar-item-2',
        name: 'Colin B Velvet H-2',
        imageSrc: './img/products/bar/colin-b-h2-velvet.jpg',
        price: 14,
      },
      {
        id: 'bar-item-3',
        name: 'C-105',
        imageSrc: './img/products/bar/c-105.jpg',
        price: 15,
      },
      {
        id: 'bar-item-4',
        name: 'C-617',
        imageSrc: './img/products/bar/c-617.jpg',
        price: 16,
      },
      {
        id: 'bar-item-5',
        name: 'Chic H-2 Velvet',
        imageSrc: './img/products/bar/chic-h2-velvet.jpg',
        price: 18,
      },
      {
        id: 'bar-item-6',
        name: 'Cherry H-2 Velvet',
        imageSrc: './img/products/bar/cherry-h2-velvet.jpg',
        price: 19,
      },
      {
        id: 'bar-item-7',
        name: 'Chic H-1 Velvet',
        imageSrc: './img/products/bar/chic-h1-velvet.jpg',
        price: 16,
      },
      {
        id: 'bar-item-8',
        name: 'Cherry H-1 Velvet',
        imageSrc: './img/products/bar/cherry-h1-velvet.jpg',
        price: 17,
      },
      {
        id: 'bar-item-9',
        name: 'C-105 Velvet',
        imageSrc: './img/products/bar/c-105-velvet.jpg',
        price: 18,
      },
      {
        id: 'bar-item-10',
        name: 'Piano B H-2 Velvet',
        imageSrc: './img/products/bar/piano-b-h2-velvet.jpg',
        price: 19,
      },
      {
        id: 'bar-item-11',
        name: 'Sting',
        imageSrc: './img/products/bar/sting.jpg',
        price: 16,
      },
      {
        id: 'bar-item-12',
        name: 'Trix H-1',
        imageSrc: './img/products/bar/trix-h1.jpg',
        price: 16,
      },
    ],
  },
  {
    id: 'children',
    title: "Children's chairs",
    path: '/children',
    imageSrc: './img/category/childrens-chair.jpg',
    items: [
      {
        id: 'children-item-1',
        name: 'Q-333',
        imageSrc: './img/products/children/q-333.jpg',
        price: 20,
      },
      {
        id: 'children-item-2',
        name: 'Q-G2',
        imageSrc: './img/products/children/q-g2.jpg',
        price: 12,
      },
      {
        id: 'children-item-3',
        name: 'Q-118R',
        imageSrc: './img/products/children/q-118r.jpg',
        price: 17,
      },
      {
        id: 'children-item-4',
        name: 'Q-330',
        imageSrc: './img/products/children/q-330.jpg',
        price: 18,
      },
      {
        id: 'children-item-5',
        name: 'Q-328H',
        imageSrc: './img/products/children/q-328h.jpg',
        price: 20,
      },
      {
        id: 'children-item-6',
        name: 'Q-328',
        imageSrc: './img/products/children/q-328.jpg',
        price: 19,
      },
      {
        id: 'children-item-7',
        name: 'Q-320',
        imageSrc: './img/products/children/q-320.jpg',
        price: 18,
      },
      {
        id: 'children-item-8',
        name: 'Q-026',
        imageSrc: './img/products/children/q-026.jpg',
        price: 17,
      },
      {
        id: 'children-item-9',
        name: 'Q-639',
        imageSrc: './img/products/children/q-639.jpg',
        price: 20,
      },
      {
        id: 'children-item-10',
        name: 'Q-121',
        imageSrc: './img/products/children/q-121.jpg',
        price: 16,
      },
      {
        id: 'children-item-11',
        name: 'Q-025',
        imageSrc: './img/products/children/q-025.jpg',
        price: 20,
      },
      {
        id: 'children-item-12',
        name: 'Q-022',
        imageSrc: './img/products/children/q-022.jpg',
        price: 17,
      },
    ],
  },
];

//For adding firestore data
// useEffect(() => {
//   addCollectionsAndDocuments('categories', DATA);
// }, []);

export default DATA;
